using System;
using System.IO;

class FinallyExample  {
    public static void Main()   {
        int a = 10;

	// Nested try-catch Block
        try {
            try {
                File.OpenRead("FIle");
                a = a/0;
            }

	    // Inner catch block
            catch (DivideByZeroException exception) {
                Console.WriteLine(exception);
            }
            Console.WriteLine("Hello");
        }
	
	// Outer catch block
        catch (Exception exception)  {
           Console.WriteLine(exception);
        }
        Console.WriteLine("Hey");
    }
}